# Generated by Django 5.2.4 on 2025-08-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qurilish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
